palavra = input('Digite algo: ')
print(type(palavra))
print(palavra.isalpha())
print(palavra.isalnum())
print(palavra.isnumeric())
print(palavra.isdecimal())
print(palavra.islower())
print(palavra.isupper())
print(palavra.isspace())
print(palavra.isascii())
